[tool.poetry]
name = "validaciones"
version = "0.1.0"
description = ""
authors = ["ruben"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pip = "^23.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
